name: Deploy to Amazon Services

on:
  pull_request:
    branches: [ "infra-*" ]
  # push:
  #   branches:
  #     - main
                                               
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt check
      id: fmt
      run: terraform fmt -check
    
    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate

    - uses: terraform-linters/setup-tflint@v3
      with:
        tflint_version: latest
        
    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -f compact

    - name: Terrform Plan
      run: "terraform plan -var-file=${{ github.ref_name }}.tfvars"
