# .github/workflows/pre-push-check.yml
name: Pre-Push Check & Create Pull Request

on:
    push:
      branches: [ "main" ]

jobs:
  pre_push_checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      run: terraform fmt --recursive

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Run TFLint
      run: tflint -f compact

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        branch: main
        title: 'Automated PR: Pre-Push Checks Passed'
        body: 'Pre-push checks have passed. Requesting review.'
        reviewers: |
          jeffcxl
          khchung1
          kristine-lim
          chrysaliswoon
